[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
ed25519-dalek = "1.0.1"
sha3 = "0.10.1"
hex-literal = "0.3.4"